TGC\AdminBundle\Entity\Project:
    type: entity
    table: project
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        startdate:
            type: date
        deadline:
            type: date
        budget:
            type: integer
            nullable: TRUE
        duration:
            type: integer
            nullable: TRUE
        description:
            type: text
        registrationtimestamp:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        status:
            type: integer
        approved:
            type: integer
            options:
              default: 0
            # columnDefinition: DEFAULT '1'
    manyToOne:
        userid:
            targetEntity: User
            inversedBy: projects
            joinColumn:
                name: business_user_id
                referencedColumnName: id
        sector:
            targetEntity: Sector
            inversedBy: projects
            joinColumn:
                name: sector_id
                referencedColumnName: id
    oneToMany:
        proposals:
            targetEntity: Proposal
            mappedBy: projectid
        contracts:
            targetEntity: Contract
            mappedBy: projectid