TGC\AdminBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        status:
            type: string
        firstName:
            type: string
        lastName:
            type: string
        location:
            type: string
        # business-specific fields
        businessName:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true
        businessDescription:
            type: text
            nullable: true
        businessWebsite:
            type: string
            nullable: true
        # consultant-specific fields
        university:
            type: string
            nullable: true
        universityEmail:
            type: string
            nullable: true
        degree:
            type: string
            nullable: true
        skills:
            type: text
            nullable: true
        tasks:
            type: text
            nullable: true
        photo:
            type: string
            nullable: true
        cv:
            type: string
            nullable: true
        linkedin:
            type: string
            nullable: true
    manyToOne:
        roleid:
            targetEntity: Role
            inversedBy: users
            joinColumn:
                name: role_id
                referencedColumnName: id
    manyToMany:
        sectors:
            targetEntity: Sector
            inversedBy: users
            joinTable:
                name: user_sector
                joinColumns:
                  user_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  sector_id:
                    referencedColumnName: id
    oneToMany:
        addresses:
            targetEntity: Address
            mappedBy: userid
        proposals:
            targetEntity: Proposal
            mappedBy: userid
        contracts:
            targetEntity: Contract
            mappedBy: userid
        projects:
            targetEntity: Project
            mappedBy: userid